#!/bin/bash

if [ "$(stat -c "%Y" "${BAMBOO_INST}/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties")" -eq "0" ]; then
  sed --in-place "s~#bamboo.home=C:\/bamboo\/bamboo-home~bamboo.home=$BAMBOO_HOME~" ${BAMBOO_INST}/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties
fi

if [ "$(stat -c "%Y" "${BAMBOO_INST}/conf/server.xml")" -eq "0" ]; then
  if [ -n "${TOMCAT_PROXY_NAME}" ]; then
    xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8085"]' --type "attr" --name "proxyName" --value "${TOMCAT_PROXY_NAME}" "${BAMBOO_INST}/conf/server.xml"
  fi
  if [ -n "${TOMCAT_PROXY_PORT}" ]; then
    xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8085"]' --type "attr" --name "proxyPort" --value "${TOMCAT_PROXY_PORT}" "${BAMBOO_INST}/conf/server.xml"
  fi
  if [ -n "${TOMCAT_PROXY_SCHEME}" ]; then
    xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8085"]' --type "attr" --name "scheme" --value "${TOMCAT_PROXY_SCHEME}" "${BAMBOO_INST}/conf/server.xml"
  fi
  if [ -n "${TOMCAT_PROXY_SECURE}" ]; then
    xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8085"]' --type "attr" --name "secure" --value "${TOMCAT_PROXY_SECURE}" "${BAMBOO_INST}/conf/server.xml"
  fi
  if [ -n "${TOMCAT_CONTEXT_PATH}" ]; then
    xmlstarlet ed --inplace --pf --ps --update '//Context/@path' --value "${TOMCAT_CONTEXT_PATH}" "${BAMBOO_INST}/conf/server.xml"
  fi
fi

if [ "$(stat -c "%Y" "${BAMBOO_INST}/bin/setenv.sh")" -eq "0" ]; then
  if [ -n "${JVM_MEMORY_MIN}" ]; then
    sed --in-place "s/JVM_MINIMUM_MEMORY=\".*\"/JVM_MINIMUM_MEMORY=\"${JVM_MEMORY_MIN}\" /" ${BAMBOO_INST}/bin/setenv.sh
  fi
  if [ -n "${JVM_MEMORY_MAX}" ]; then
    sed --in-place "s/JVM_MAXIMUM_MEMORY=\".*\"/JVM_MAXIMUM_MEMORY=\"${JVM_MEMORY_MAX}\" /" ${BAMBOO_INST}/bin/setenv.sh
  fi
fi

nohup ${BAMBOO_INST}/bin/start-bamboo.sh >/dev/null 2>&1 &

/bin/bash
